on:
  workflow_dispatch:
    inputs:
      tags:
  push:
    tags:
      - "*"
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

name: build
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          cd CookieKatz-BOF && nmake all && nmake all-debug
      - name: ZipIt
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          path: '@zip.lst'
          filename: 'CookieKatz.zip'
          command: 'echo ./ >> zip.lst'
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: CookieKatz.zip
